<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="8d8d57ff-88a6-472c-85d3-d57ec2e78879" name="simmon@SIMMON-PC 2012-03-21 17:14:19" runUser="simmon-PC\simmon" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="f3e4f830-58d2-476d-86e4-89d57190b36c">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="simmon_SIMMON-PC 2012-03-21 17_14_19">
      <DeploymentItem filename="C:\Program Files (x86)\NUnit 2.6\bin\framework\nunit.framework.dll" />
      <DeploymentItem filename="C:\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\MyFileSystemWatcherText\bin\Debug\MyFileSystemWatcherText.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-03-21T17:14:19.6867669+08:00" queuing="2012-03-21T17:14:19.7117683+08:00" start="2012-03-21T17:14:19.7287693+08:00" finish="2012-03-21T17:14:20.8196118+08:00" />
  <ResultSummary outcome="Error">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
    <RunInfos>
      <RunInfo computerName="SIMMON-PC" outcome="Error" timestamp="2012-03-21T17:14:20.5544113+08:00">
        <Text>One of the background threads threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at text.MyFileSystemWather.WatcherProcess_OnChanged(Object sender, FileSystemEventArgs e) in C:\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\MyFileSystemWatcherText\MYFileSystemWatcher.cs:line 186
   at text.WatcherProcess.Process() in C:\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\MyFileSystemWatcherText\WatcherProcess.cs:line 44
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</Text>
      </RunInfo>
      <RunInfo computerName="SIMMON-PC" outcome="Error" timestamp="2012-03-21T17:14:20.5544113+08:00">
        <Text>One of the background threads threw exception: 
System.ArgumentException: Item has already been added. Key in dictionary: 'C:/\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\TestResults\simmon_SIMMON-PC 2012-03-21 17_14_19\Out\AgentRestart.dat'  Key being added: 'C:/\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\TestResults\simmon_SIMMON-PC 2012-03-21 17_14_19\Out\AgentRestart.dat'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.Add(Object key, Object value)
   at text.MyFileSystemWather.fsWather_Deleted(Object sender, FileSystemEventArgs e) in C:\Users\simmon\Documents\Visual Studio 2010\Projects\MyFileSystemWatcherText\MyFileSystemWatcherText\MYFileSystemWatcher.cs:line 145
   at System.IO.FileSystemWatcher.OnDeleted(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.NotifyFileSystemEventArgs(Int32 action, String name)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.IOCompletionCallback_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="StartTest" storage="c:\users\simmon\documents\visual studio 2010\projects\myfilesystemwatchertext\testproject1\bin\debug\testproject1.dll" id="88ec4445-7742-e261-a8a4-eba7713570b8">
      <Execution id="cc5b4276-a95f-42fc-b80b-6398c4aaf3c8" />
      <TestMethod codeBase="C:/Users/simmon/Documents/Visual Studio 2010/Projects/MyFileSystemWatcherText/TestProject1/bin/Debug/TestProject1.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestProject1.MyFileSystemWatherTest, TestProject1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="StartTest" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="88ec4445-7742-e261-a8a4-eba7713570b8" executionId="cc5b4276-a95f-42fc-b80b-6398c4aaf3c8" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="cc5b4276-a95f-42fc-b80b-6398c4aaf3c8" testId="88ec4445-7742-e261-a8a4-eba7713570b8" testName="StartTest" computerName="SIMMON-PC" duration="00:00:00.0520625" startTime="2012-03-21T17:14:19.7407700+08:00" endTime="2012-03-21T17:14:20.0237862+08:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="cc5b4276-a95f-42fc-b80b-6398c4aaf3c8">
      <Output>
        <ErrorInfo>
          <Message>Test method TestProject1.MyFileSystemWatherTest.StartTest did not throw expected exception System.Exception. 找不到路径：C:/</Message>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>